# Feed RihkyeTask dataset into an Elman RNN model

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sys, shelve

import torch
import torch.nn as nn

from task import RihkyeTask

In [4]:
RNGSEED = 5
np.random.seed([RNGSEED])

num_cueingcontext = 2
num_cue = 2
num_rule = 2
rule = [0, 1, 0, 1]
blocklen = [500, 500, 200]
block_cueingcontext = [0, 1, 0]
tsteps = 200
cuesteps = 100
batch_size = 10

dataset = RihkyeTask(num_cueingcontext=num_cueingcontext, num_cue=num_cue, num_rule=num_rule, rule=rule, blocklen=blocklen, \
block_cueingcontext=block_cueingcontext, tsteps=tsteps, cuesteps=cuesteps, batch_size=batch_size)

input, target = dataset()
print(input.shape, target.shape, '\n')
print(input[210:220, 9, :])
print(target[210:220, 9, :])

(400, 10, 4) (400, 10, 2) 

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


In [50]:
a = np.array([[0, 1], [0, 0]])
a = np.random.permutation(a)
print(a)

[[0 0]
 [0 1]]


- cue, target = dataset.get_cue_target(taski=0, cuei=0) cue should be \[1, -1, 0, 0\]?
- do use one-hot coding in targets
- in a training step, we select one cueing context (e.g. noise context), then we give two trials, high-pass noise and low-pass noise, in a random sequence. 500 training steps like this consist of a training block. In the next training block, we will select another cueing context.
- batch size?